/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BO.AccountBO;
import javax.swing.JOptionPane;
import util.ColorForm;
import util.Effect;
import util.FormController;
import util.Support;

/**
 *
 * @author Trần Việt
 */
public class ForgotPass extends javax.swing.JFrame {

    AccountBO accountBO = new AccountBO();
    Effect effect = new Effect();
    private boolean isDark;

    /**
     * Creates new form ForgotPass
     */
    public ForgotPass(boolean isDark) {
        initComponents();
        getRandomCode();
        setLocationRelativeTo(null);
        this.isDark = isDark;
        setColor();
    }

    public void getRandomCode() {
        jlbRandomCode.setText(new Support().RandomCode());
    }

    public void setColor() {
        ColorForm color = new ColorForm();

        color.PanelMouseEvent(isDark, jpnOK);
        color.LabelMouseEvent(isDark, jlbLogin);
        color.PanelBackGround(isDark, jpnBoderCenter, jpnBoderEnd, jpnBoderHead, jpnMain, jpnOK);
        color.JTextfierdBackGround(isDark, jtfEnterCode, txtPIN, txtUserName);
        color.LabelBackGround(isDark, jLabel1, jLabel2, jLabel3, jLabel6, jlbNewCode, jlbOK, jlbRandomCode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popMenu = new javax.swing.JPopupMenu();
        popSignIn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        popDark = new javax.swing.JMenuItem();
        popWhite = new javax.swing.JMenuItem();
        popExit = new javax.swing.JMenuItem();
        jpnMain = new javax.swing.JPanel();
        jpnBoderHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnBoderCenter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPIN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jlbRandomCode = new javax.swing.JLabel();
        jlbNewCode = new javax.swing.JLabel();
        jtfEnterCode = new javax.swing.JTextField();
        jpnBoderEnd = new javax.swing.JPanel();
        jpnOK = new javax.swing.JPanel();
        jlbOK = new javax.swing.JLabel();
        jlbLogin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSignIn = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDark = new javax.swing.JMenuItem();
        menuWhite = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        popSignIn.setText("Sign In");
        popSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popSignInActionPerformed(evt);
            }
        });
        popMenu.add(popSignIn);

        jMenu4.setText("Change background");

        popDark.setText("Dark background");
        popDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popDarkActionPerformed(evt);
            }
        });
        jMenu4.add(popDark);

        popWhite.setText("White background");
        popWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popWhiteActionPerformed(evt);
            }
        });
        jMenu4.add(popWhite);

        popMenu.add(jMenu4);

        popExit.setText("Exit");
        popExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popExitActionPerformed(evt);
            }
        });
        popMenu.add(popExit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jpnMain.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Question Below:");

        javax.swing.GroupLayout jpnBoderHeadLayout = new javax.swing.GroupLayout(jpnBoderHead);
        jpnBoderHead.setLayout(jpnBoderHeadLayout);
        jpnBoderHeadLayout.setHorizontalGroup(
            jpnBoderHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBoderHeadLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jpnBoderHeadLayout.setVerticalGroup(
            jpnBoderHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBoderHeadLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jpnMain.add(jpnBoderHead, java.awt.BorderLayout.PAGE_START);

        jpnBoderCenter.setPreferredSize(new java.awt.Dimension(520, 450));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Enter Your UserName:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Enter Your Secret PIN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Please Enter the Code:");

        jlbRandomCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRandomCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlbNewCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbNewCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNewCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh_32px.png"))); // NOI18N
        jlbNewCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlbNewCode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbNewCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNewCodeMouseClicked(evt);
            }
        });

        jtfEnterCode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout jpnBoderCenterLayout = new javax.swing.GroupLayout(jpnBoderCenter);
        jpnBoderCenter.setLayout(jpnBoderCenterLayout);
        jpnBoderCenterLayout.setHorizontalGroup(
            jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                                .addComponent(jlbRandomCode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jlbNewCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jtfEnterCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jpnBoderCenterLayout.setVerticalGroup(
            jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnBoderCenterLayout.createSequentialGroup()
                        .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jpnBoderCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbRandomCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbNewCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jtfEnterCode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnMain.add(jpnBoderCenter, java.awt.BorderLayout.CENTER);

        jpnBoderEnd.setPreferredSize(new java.awt.Dimension(520, 100));

        jpnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnOKMouseClicked(evt);
            }
        });

        jlbOK.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jlbOK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbOK.setText("OK");

        javax.swing.GroupLayout jpnOKLayout = new javax.swing.GroupLayout(jpnOK);
        jpnOK.setLayout(jpnOKLayout);
        jpnOKLayout.setHorizontalGroup(
            jpnOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbOK, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
        );
        jpnOKLayout.setVerticalGroup(
            jpnOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbOK, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jlbLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_rounded_right_32px.png"))); // NOI18N
        jlbLogin.setText("Login");
        jlbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnBoderEndLayout = new javax.swing.GroupLayout(jpnBoderEnd);
        jpnBoderEnd.setLayout(jpnBoderEndLayout);
        jpnBoderEndLayout.setHorizontalGroup(
            jpnBoderEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBoderEndLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jlbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jpnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jpnBoderEndLayout.setVerticalGroup(
            jpnBoderEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBoderEndLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jpnBoderEndLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpnMain.add(jpnBoderEnd, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("File");

        menuSignIn.setText("Sign In");
        menuSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignInActionPerformed(evt);
            }
        });
        jMenu1.add(menuSignIn);

        jMenu3.setText("Change Background");

        menuDark.setText("dark background");
        menuDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDarkActionPerformed(evt);
            }
        });
        jMenu3.add(menuDark);

        menuWhite.setText("white background");
        menuWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWhiteActionPerformed(evt);
            }
        });
        jMenu3.add(menuWhite);

        jMenu1.add(jMenu3);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbNewCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNewCodeMouseClicked
        getRandomCode();
    }//GEN-LAST:event_jlbNewCodeMouseClicked

    private void jpnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnOKMouseClicked
        if (jlbRandomCode.getText().equals(jtfEnterCode.getText())) {
            effect.LoadingMouse(this, true);
            accountBO.GetPass(this, isDark, txtUserName.getText(), txtPIN.getText());
            getRandomCode();

        } else {
            JOptionPane.showMessageDialog(this, "Enter wrong Code");
            getRandomCode();
        }

    }//GEN-LAST:event_jpnOKMouseClicked

    private void menuWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWhiteActionPerformed
        isDark = false;
        setColor();

    }//GEN-LAST:event_menuWhiteActionPerformed

    private void menuDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDarkActionPerformed
        isDark = true;
        setColor();
    }//GEN-LAST:event_menuDarkActionPerformed

    private void menuSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignInActionPerformed
        this.dispose();
        new FormController().show(new SignIn(isDark));
    }//GEN-LAST:event_menuSignInActionPerformed

    private void popExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_popExitActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void popSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popSignInActionPerformed
        this.dispose();
        new FormController().show(new SignIn(isDark));
    }//GEN-LAST:event_popSignInActionPerformed

    private void popDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popDarkActionPerformed
        isDark = true;
        setColor();
    }//GEN-LAST:event_popDarkActionPerformed

    private void popWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popWhiteActionPerformed
        isDark = false;
        setColor();
    }//GEN-LAST:event_popWhiteActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
       if (evt.getButton() == 3) {
            popMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void jlbLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLoginMouseClicked
        this.dispose();
        new FormController().show(new SignIn(isDark));
    }//GEN-LAST:event_jlbLoginMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlbLogin;
    private javax.swing.JLabel jlbNewCode;
    private javax.swing.JLabel jlbOK;
    private javax.swing.JLabel jlbRandomCode;
    private javax.swing.JPanel jpnBoderCenter;
    private javax.swing.JPanel jpnBoderEnd;
    private javax.swing.JPanel jpnBoderHead;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnOK;
    private javax.swing.JTextField jtfEnterCode;
    private javax.swing.JMenuItem menuDark;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuSignIn;
    private javax.swing.JMenuItem menuWhite;
    private javax.swing.JMenuItem popDark;
    private javax.swing.JMenuItem popExit;
    private javax.swing.JPopupMenu popMenu;
    private javax.swing.JMenuItem popSignIn;
    private javax.swing.JMenuItem popWhite;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
