/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BO.AccountBO;
import BO.StudentBO;
import DAO.AccountDAO;
import DAO.StudentDAO;
import entity.Account;
import entity.Student;
import gui.dialog.StudentInfor;
import java.awt.CardLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import util.ColorForm;
import util.Effect;
import util.FormController;
import util.ImageShow;

/**
 *
 * @author Trần Việt
 */
public class Main extends javax.swing.JFrame {

    Account isNow;
    FormController controller = new FormController();
    ColorForm color = new ColorForm();
    StudentBO studentBO = new StudentBO();
    AccountBO accountBO = new AccountBO();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        Effect(false);

        setLocationRelativeTo(null);
    }

    public Main(Account now) {
        initComponents();
        this.isNow = now;
        showUp();
        Effect(false);
        setLocationRelativeTo(null);
    }

    public void showUp() {
        new Effect().mainSetUp(jpnMenuOption, isNow, jlbLogout, jlbMenuOption, jLabel3);
    }

    public void Effect(boolean isDark) {
        color.PanelMouseEvent(isDark, jpnStuShow, jpnStuRefresh, jpnStuSearch,
                jpnStudent, jpnStuAdd, jpnStuDelete, jpnStuUpdate, jpnAccount,
                 jpnAccRefresh, jpnAccSearch, jpnAccShow
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnGlobal = new javax.swing.JPanel();
        jpnOption = new javax.swing.JPanel();
        jpnInformation = new javax.swing.JPanel();
        jlbLogout = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbMenuOption = new javax.swing.JLabel();
        jpnMenuOption = new javax.swing.JPanel();
        jpnAccount = new javax.swing.JPanel();
        jlbAccount = new javax.swing.JLabel();
        jpnStudent = new javax.swing.JPanel();
        jlbStudent = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jpnTotalInfor = new javax.swing.JPanel();
        jpnHandling = new javax.swing.JPanel();
        jpnDefaultOption = new javax.swing.JPanel();
        jpnAccountOption = new javax.swing.JPanel();
        jlbAccountTotal = new javax.swing.JLabel();
        jlbAccAdmin = new javax.swing.JLabel();
        jlbAccTeacher = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtAccSearch = new javax.swing.JTextField();
        jpnAccSearch = new javax.swing.JPanel();
        jlbAccSearch = new javax.swing.JLabel();
        jpnAccRefresh = new javax.swing.JPanel();
        jlbAccRefresh = new javax.swing.JLabel();
        jpnAccShow = new javax.swing.JPanel();
        jlbAccShow = new javax.swing.JLabel();
        jlbAccStudent = new javax.swing.JLabel();
        jlbAccOutside = new javax.swing.JLabel();
        jpnStudentOption = new javax.swing.JPanel();
        jlbStudentTotal = new javax.swing.JLabel();
        jlbStudentMale = new javax.swing.JLabel();
        jlbStudentFemale = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jpnStuSearch = new javax.swing.JPanel();
        jlbStuSearch = new javax.swing.JLabel();
        jpnStuRefresh = new javax.swing.JPanel();
        jlbStuReFresh = new javax.swing.JLabel();
        jpnStuShow = new javax.swing.JPanel();
        jlbStuShow = new javax.swing.JLabel();
        jpnStuDelete = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpnStuAdd = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jlbIsStudy = new javax.swing.JLabel();
        jlbNotStudy = new javax.swing.JLabel();
        jpnStuUpdate = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jpnDomOption = new javax.swing.JPanel();
        jpnTable = new javax.swing.JPanel();
        jpnDefault = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpnAccountDetail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbAccount = new javax.swing.JTable();
        jpnStudentDetail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbStudent = new javax.swing.JTable();
        jpnDom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnGlobal.setLayout(new java.awt.BorderLayout());

        jpnOption.setPreferredSize(new java.awt.Dimension(200, 750));
        jpnOption.setLayout(new java.awt.BorderLayout());

        jpnInformation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnInformation.setPreferredSize(new java.awt.Dimension(250, 150));

        jlbLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logout_rounded_left_48px.png"))); // NOI18N
        jlbLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbLogoutMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_male_30px.png"))); // NOI18N
        jLabel3.setText("Dương");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlbMenuOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/menu_48px.png"))); // NOI18N
        jlbMenuOption.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbMenuOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbMenuOptionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnInformationLayout = new javax.swing.GroupLayout(jpnInformation);
        jpnInformation.setLayout(jpnInformationLayout);
        jpnInformationLayout.setHorizontalGroup(
            jpnInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInformationLayout.createSequentialGroup()
                .addComponent(jlbMenuOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jlbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jpnInformationLayout.setVerticalGroup(
            jpnInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMenuOption)))
        );

        jpnOption.add(jpnInformation, java.awt.BorderLayout.PAGE_START);

        jpnMenuOption.setLayout(new java.awt.GridLayout(0, 1));

        jpnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAccountMouseClicked(evt);
            }
        });

        jlbAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAccount.setText("Account");

        javax.swing.GroupLayout jpnAccountLayout = new javax.swing.GroupLayout(jpnAccount);
        jpnAccount.setLayout(jpnAccountLayout);
        jpnAccountLayout.setHorizontalGroup(
            jpnAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpnAccountLayout.setVerticalGroup(
            jpnAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jpnAccount);

        jpnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStudentMouseClicked(evt);
            }
        });

        jlbStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbStudent.setText("Student");

        javax.swing.GroupLayout jpnStudentLayout = new javax.swing.GroupLayout(jpnStudent);
        jpnStudent.setLayout(jpnStudentLayout);
        jpnStudentLayout.setHorizontalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jpnStudentLayout.setVerticalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudent, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jpnStudent);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DOM");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jPanel11);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel1");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jPanel12);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jPanel14);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jPanel13);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jpnMenuOption.add(jPanel10);

        jpnOption.add(jpnMenuOption, java.awt.BorderLayout.CENTER);

        jpnGlobal.add(jpnOption, java.awt.BorderLayout.WEST);

        jpnTotalInfor.setLayout(new java.awt.BorderLayout());

        jpnHandling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpnHandling.setPreferredSize(new java.awt.Dimension(950, 200));
        jpnHandling.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jpnDefaultOptionLayout = new javax.swing.GroupLayout(jpnDefaultOption);
        jpnDefaultOption.setLayout(jpnDefaultOptionLayout);
        jpnDefaultOptionLayout.setHorizontalGroup(
            jpnDefaultOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        jpnDefaultOptionLayout.setVerticalGroup(
            jpnDefaultOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jpnHandling.add(jpnDefaultOption, "card2");

        jpnAccountOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbAccountTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAccountTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_32px.png"))); // NOI18N
        jlbAccountTotal.setText("Total:");
        jlbAccountTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnAccountOption.add(jlbAccountTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jlbAccAdmin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAccAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_male_30px.png"))); // NOI18N
        jlbAccAdmin.setText("Admin:");
        jlbAccAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAccAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAccAdminMouseClicked(evt);
            }
        });
        jpnAccountOption.add(jlbAccAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jlbAccTeacher.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAccTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_female_30px.png"))); // NOI18N
        jlbAccTeacher.setText("Teacher:");
        jlbAccTeacher.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAccTeacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAccTeacherMouseClicked(evt);
            }
        });
        jpnAccountOption.add(jlbAccTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("Search By User Name:");
        jpnAccountOption.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, 35));

        txtAccSearch.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnAccountOption.add(txtAccSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 210, 35));

        jpnAccSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAccSearchMouseClicked(evt);
            }
        });

        jlbAccSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbAccSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAccSearch.setText("Search");

        javax.swing.GroupLayout jpnAccSearchLayout = new javax.swing.GroupLayout(jpnAccSearch);
        jpnAccSearch.setLayout(jpnAccSearchLayout);
        jpnAccSearchLayout.setHorizontalGroup(
            jpnAccSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnAccSearchLayout.setVerticalGroup(
            jpnAccSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAccSearchLayout.createSequentialGroup()
                .addComponent(jlbAccSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnAccountOption.add(jpnAccSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 21, -1, -1));

        jpnAccRefresh.setPreferredSize(new java.awt.Dimension(60, 60));
        jpnAccRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAccRefreshMouseClicked(evt);
            }
        });

        jlbAccRefresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAccRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh_32px.png"))); // NOI18N

        javax.swing.GroupLayout jpnAccRefreshLayout = new javax.swing.GroupLayout(jpnAccRefresh);
        jpnAccRefresh.setLayout(jpnAccRefreshLayout);
        jpnAccRefreshLayout.setHorizontalGroup(
            jpnAccRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jpnAccRefreshLayout.setVerticalGroup(
            jpnAccRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnAccountOption.add(jpnAccRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, 60));

        jpnAccShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnAccShowMouseClicked(evt);
            }
        });

        jlbAccShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbAccShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAccShow.setText("Show");

        javax.swing.GroupLayout jpnAccShowLayout = new javax.swing.GroupLayout(jpnAccShow);
        jpnAccShow.setLayout(jpnAccShowLayout);
        jpnAccShowLayout.setHorizontalGroup(
            jpnAccShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccShow, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnAccShowLayout.setVerticalGroup(
            jpnAccShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbAccShow, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnAccountOption.add(jpnAccShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        jlbAccStudent.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAccStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_center_24px.png"))); // NOI18N
        jlbAccStudent.setText("Student:");
        jlbAccStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAccStudent.setPreferredSize(new java.awt.Dimension(62, 30));
        jlbAccStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAccStudentMouseClicked(evt);
            }
        });
        jpnAccountOption.add(jlbAccStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, -1));

        jlbAccOutside.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbAccOutside.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_center2_24px.png"))); // NOI18N
        jlbAccOutside.setText("Parents:");
        jlbAccOutside.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbAccOutside.setPreferredSize(new java.awt.Dimension(95, 30));
        jlbAccOutside.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbAccOutsideMouseClicked(evt);
            }
        });
        jpnAccountOption.add(jlbAccOutside, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 130, -1));

        jpnHandling.add(jpnAccountOption, "Account");

        jpnStudentOption.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbStudentTotal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbStudentTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_32px.png"))); // NOI18N
        jlbStudentTotal.setText("Total:");
        jlbStudentTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpnStudentOption.add(jlbStudentTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jlbStudentMale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbStudentMale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_male_30px.png"))); // NOI18N
        jlbStudentMale.setText("Male:");
        jlbStudentMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbStudentMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbStudentMaleMouseClicked(evt);
            }
        });
        jpnStudentOption.add(jlbStudentMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jlbStudentFemale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbStudentFemale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user_female_30px.png"))); // NOI18N
        jlbStudentFemale.setText("Female:");
        jlbStudentFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbStudentFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbStudentFemaleMouseClicked(evt);
            }
        });
        jpnStudentOption.add(jlbStudentFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("Search By:");
        jpnStudentOption.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 29, 83, 35));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnStudentOption.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 29, 180, 35));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Roll Number", "  Name", "  Date of Birth", "  Address", "  Sesion" }));
        jpnStudentOption.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(822, 29, 130, 35));

        jpnStuSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuSearchMouseClicked(evt);
            }
        });

        jlbStuSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jlbStuSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbStuSearch.setText("Search");

        javax.swing.GroupLayout jpnStuSearchLayout = new javax.swing.GroupLayout(jpnStuSearch);
        jpnStuSearch.setLayout(jpnStuSearchLayout);
        jpnStuSearchLayout.setHorizontalGroup(
            jpnStuSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStuSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnStuSearchLayout.setVerticalGroup(
            jpnStuSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStuSearchLayout.createSequentialGroup()
                .addComponent(jlbStuSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnStudentOption.add(jpnStuSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(971, 21, -1, -1));

        jpnStuRefresh.setPreferredSize(new java.awt.Dimension(60, 60));
        jpnStuRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuRefreshMouseClicked(evt);
            }
        });

        jlbStuReFresh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbStuReFresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh_32px.png"))); // NOI18N

        javax.swing.GroupLayout jpnStuRefreshLayout = new javax.swing.GroupLayout(jpnStuRefresh);
        jpnStuRefresh.setLayout(jpnStuRefreshLayout);
        jpnStuRefreshLayout.setHorizontalGroup(
            jpnStuRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStuReFresh, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        jpnStuRefreshLayout.setVerticalGroup(
            jpnStuRefreshLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStuReFresh, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnStudentOption.add(jpnStuRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, -1, 60));

        jpnStuShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuShowMouseClicked(evt);
            }
        });

        jlbStuShow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbStuShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbStuShow.setText("Show");

        javax.swing.GroupLayout jpnStuShowLayout = new javax.swing.GroupLayout(jpnStuShow);
        jpnStuShow.setLayout(jpnStuShowLayout);
        jpnStuShowLayout.setHorizontalGroup(
            jpnStuShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStuShow, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnStuShowLayout.setVerticalGroup(
            jpnStuShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStuShow, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnStudentOption.add(jpnStuShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));

        jpnStuDelete.setPreferredSize(new java.awt.Dimension(100, 60));
        jpnStuDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuDeleteMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Delete");

        javax.swing.GroupLayout jpnStuDeleteLayout = new javax.swing.GroupLayout(jpnStuDelete);
        jpnStuDelete.setLayout(jpnStuDeleteLayout);
        jpnStuDeleteLayout.setHorizontalGroup(
            jpnStuDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnStuDeleteLayout.setVerticalGroup(
            jpnStuDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnStudentOption.add(jpnStuDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jpnStuAdd.setPreferredSize(new java.awt.Dimension(100, 60));
        jpnStuAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuAddMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Add");

        javax.swing.GroupLayout jpnStuAddLayout = new javax.swing.GroupLayout(jpnStuAdd);
        jpnStuAdd.setLayout(jpnStuAddLayout);
        jpnStuAddLayout.setHorizontalGroup(
            jpnStuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnStuAddLayout.setVerticalGroup(
            jpnStuAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnStudentOption.add(jpnStuAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jlbIsStudy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbIsStudy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_center_24px.png"))); // NOI18N
        jlbIsStudy.setText("Study");
        jlbIsStudy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbIsStudy.setPreferredSize(new java.awt.Dimension(62, 30));
        jlbIsStudy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbIsStudyMouseClicked(evt);
            }
        });
        jpnStudentOption.add(jlbIsStudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, -1));

        jlbNotStudy.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbNotStudy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/student_center2_24px.png"))); // NOI18N
        jlbNotStudy.setText("Tạm Dừng:");
        jlbNotStudy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbNotStudy.setPreferredSize(new java.awt.Dimension(95, 30));
        jlbNotStudy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNotStudyMouseClicked(evt);
            }
        });
        jpnStudentOption.add(jlbNotStudy, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 130, -1));

        jpnStuUpdate.setPreferredSize(new java.awt.Dimension(100, 60));
        jpnStuUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnStuUpdateMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Update");

        javax.swing.GroupLayout jpnStuUpdateLayout = new javax.swing.GroupLayout(jpnStuUpdate);
        jpnStuUpdate.setLayout(jpnStuUpdateLayout);
        jpnStuUpdateLayout.setHorizontalGroup(
            jpnStuUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnStuUpdateLayout.setVerticalGroup(
            jpnStuUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpnStudentOption.add(jpnStuUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jpnHandling.add(jpnStudentOption, "Student");

        javax.swing.GroupLayout jpnDomOptionLayout = new javax.swing.GroupLayout(jpnDomOption);
        jpnDomOption.setLayout(jpnDomOptionLayout);
        jpnDomOptionLayout.setHorizontalGroup(
            jpnDomOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        jpnDomOptionLayout.setVerticalGroup(
            jpnDomOptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        jpnHandling.add(jpnDomOption, "card5");

        jpnTotalInfor.add(jpnHandling, java.awt.BorderLayout.PAGE_START);

        jpnTable.setPreferredSize(new java.awt.Dimension(1100, 550));
        jpnTable.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Design  by Trần Quang Việt");

        javax.swing.GroupLayout jpnDefaultLayout = new javax.swing.GroupLayout(jpnDefault);
        jpnDefault.setLayout(jpnDefaultLayout);
        jpnDefaultLayout.setHorizontalGroup(
            jpnDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDefaultLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpnDefaultLayout.setVerticalGroup(
            jpnDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDefaultLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jpnTable.add(jpnDefault, "default");

        jtbAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  STT", "  User Name", "  PassWord", "  Secret Text", "  Type", "  Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbAccount.setRowHeight(25);
        jScrollPane2.setViewportView(jtbAccount);
        if (jtbAccount.getColumnModel().getColumnCount() > 0) {
            jtbAccount.getColumnModel().getColumn(0).setMinWidth(50);
            jtbAccount.getColumnModel().getColumn(0).setMaxWidth(50);
            jtbAccount.getColumnModel().getColumn(1).setMinWidth(200);
            jtbAccount.getColumnModel().getColumn(1).setMaxWidth(200);
            jtbAccount.getColumnModel().getColumn(2).setMinWidth(200);
            jtbAccount.getColumnModel().getColumn(2).setMaxWidth(200);
            jtbAccount.getColumnModel().getColumn(4).setMinWidth(180);
            jtbAccount.getColumnModel().getColumn(4).setMaxWidth(180);
            jtbAccount.getColumnModel().getColumn(5).setMinWidth(150);
            jtbAccount.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout jpnAccountDetailLayout = new javax.swing.GroupLayout(jpnAccountDetail);
        jpnAccountDetail.setLayout(jpnAccountDetailLayout);
        jpnAccountDetailLayout.setHorizontalGroup(
            jpnAccountDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jpnAccountDetailLayout.setVerticalGroup(
            jpnAccountDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jpnTable.add(jpnAccountDetail, "Account");

        jScrollPane1.setBorder(null);

        jtbStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Roll Number", "Full Name", "Gender", "Date of Birth", "Address", "Sesion", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbStudent.setAlignmentX(1.0F);
        jtbStudent.setAlignmentY(1.0F);
        jtbStudent.setRowHeight(25);
        jtbStudent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtbStudentFocusLost(evt);
            }
        });
        jtbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbStudent);
        if (jtbStudent.getColumnModel().getColumnCount() > 0) {
            jtbStudent.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtbStudent.getColumnModel().getColumn(0).setMaxWidth(50);
            jtbStudent.getColumnModel().getColumn(1).setMinWidth(120);
            jtbStudent.getColumnModel().getColumn(1).setMaxWidth(120);
            jtbStudent.getColumnModel().getColumn(2).setMinWidth(250);
            jtbStudent.getColumnModel().getColumn(2).setMaxWidth(250);
            jtbStudent.getColumnModel().getColumn(3).setMinWidth(100);
            jtbStudent.getColumnModel().getColumn(3).setMaxWidth(100);
            jtbStudent.getColumnModel().getColumn(5).setMinWidth(230);
            jtbStudent.getColumnModel().getColumn(5).setMaxWidth(230);
            jtbStudent.getColumnModel().getColumn(6).setMinWidth(80);
            jtbStudent.getColumnModel().getColumn(6).setMaxWidth(80);
            jtbStudent.getColumnModel().getColumn(7).setMinWidth(140);
            jtbStudent.getColumnModel().getColumn(7).setMaxWidth(140);
        }

        javax.swing.GroupLayout jpnStudentDetailLayout = new javax.swing.GroupLayout(jpnStudentDetail);
        jpnStudentDetail.setLayout(jpnStudentDetailLayout);
        jpnStudentDetailLayout.setHorizontalGroup(
            jpnStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jpnStudentDetailLayout.setVerticalGroup(
            jpnStudentDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        jpnTable.add(jpnStudentDetail, "Student");

        javax.swing.GroupLayout jpnDomLayout = new javax.swing.GroupLayout(jpnDom);
        jpnDom.setLayout(jpnDomLayout);
        jpnDomLayout.setHorizontalGroup(
            jpnDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jpnDomLayout.setVerticalGroup(
            jpnDomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jpnTable.add(jpnDom, "DOM");

        jpnTotalInfor.add(jpnTable, java.awt.BorderLayout.CENTER);

        jpnGlobal.add(jpnTotalInfor, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnGlobal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Student> listStu = new ArrayList<>();
    List<Student> listStuUse = new ArrayList<>();
    List<Account> listAcc = new ArrayList<>();
    List<Account> listAccUse = new ArrayList<>();
    boolean menuOption = false;
    int s1 = -1, s2 = -1;
    boolean click = true;

    private void jlbMenuOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbMenuOptionMouseClicked
        controller.showOption(jpnMenuOption, jlbMenuOption, menuOption);
        menuOption = !menuOption;
    }//GEN-LAST:event_jlbMenuOptionMouseClicked

    private void jlbLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLogoutMouseClicked
        controller.show(new SignIn(true));
        this.dispose();
    }//GEN-LAST:event_jlbLogoutMouseClicked

    private void jlbStudentMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbStudentMaleMouseClicked
        listStuUse = studentBO.showGender(jtbStudent, listStu, true);
        s1 = s2 = -1;
    }//GEN-LAST:event_jlbStudentMaleMouseClicked

    private void jlbStudentFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbStudentFemaleMouseClicked
        listStuUse = studentBO.showGender(jtbStudent, listStu, false);
        s1 = s2 = -1;
    }//GEN-LAST:event_jlbStudentFemaleMouseClicked

    private void jpnStuShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuShowMouseClicked
        listStu = studentBO.showList(jtbStudent);
        listStuUse = new ArrayList<>(listStu);

        studentBO.count(listStu, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
    }//GEN-LAST:event_jpnStuShowMouseClicked

    private void jpnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStudentMouseClicked
        controller.changePanel(jpnTable, jpnHandling, jlbStudent.getText());
    }//GEN-LAST:event_jpnStudentMouseClicked

    private void jlbIsStudyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbIsStudyMouseClicked
        listStuUse = studentBO.showStudy(jtbStudent, listStu, true);
        s1 = s2 = -1;
    }//GEN-LAST:event_jlbIsStudyMouseClicked

    private void jlbNotStudyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNotStudyMouseClicked
        listStuUse = studentBO.showStudy(jtbStudent, listStu, false);
        s1 = s2 = -1;
    }//GEN-LAST:event_jlbNotStudyMouseClicked

    private void jpnStuRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuRefreshMouseClicked
        studentBO.displayListStudent(jtbStudent, listStu);
        listStuUse = new ArrayList<>(listStu);
        studentBO.count(listStuUse, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
        s1 = s2 = -1;
    }//GEN-LAST:event_jpnStuRefreshMouseClicked

    private void jpnStuAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuAddMouseClicked
        if (isNow.getType() != 0) {
            JOptionPane.showMessageDialog(this, "Sory!!You cann't change data!!", "Warnning", JOptionPane.WARNING_MESSAGE);
        } else {
            controller.show(new StudentInfor(this, true));
        }
        studentBO.count(listStuUse, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
    }//GEN-LAST:event_jpnStuAddMouseClicked

    private void jpnStuUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuUpdateMouseClicked
        studentBO.updateStudent(this, getAction, isNow, listStu, jtbStudent.getSelectedRow());
    }//GEN-LAST:event_jpnStuUpdateMouseClicked

    private void jpnStuDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuDeleteMouseClicked
        studentBO.deleteStudent(this, isNow, listStu, jtbStudent, jtbStudent.getSelectedRow());
        studentBO.count(listStuUse, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
    }//GEN-LAST:event_jpnStuDeleteMouseClicked

    private void jpnStuSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnStuSearchMouseClicked

        listStuUse = new StudentBO().searchStudent(listStu, jComboBox1.getSelectedIndex(), jTextField1.getText());
        studentBO.displayListStudent(jtbStudent, listStuUse);
        studentBO.count(listStuUse, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
        s1 = s2 = -1;
    }//GEN-LAST:event_jpnStuSearchMouseClicked

    private void jpnAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAccountMouseClicked
        controller.changePanel(jpnTable, jpnHandling, jlbAccount.getText());
    }//GEN-LAST:event_jpnAccountMouseClicked

    private void jtbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbStudentMouseClicked
        if (click) {
            s1 = jtbStudent.getSelectedRow();
        } else {
            s2 = jtbStudent.getSelectedRow();
        }
        click = !click;
        if (s1 == s2) {
            StudentInfor stu = new StudentInfor(this, true, listStuUse.get(s1), false);
            stu.addWindowListener(getAction);
            controller.show(stu);
        }
    }//GEN-LAST:event_jtbStudentMouseClicked

    private void jtbStudentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbStudentFocusLost
        s1 = s2 = -1;
    }//GEN-LAST:event_jtbStudentFocusLost

    private void jlbAccAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAccAdminMouseClicked
        listAccUse = accountBO.Listed(0, listAcc);
        accountBO.displayListAccount(jtbAccount, listAccUse);
    }//GEN-LAST:event_jlbAccAdminMouseClicked

    private void jlbAccTeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAccTeacherMouseClicked
        listAccUse = accountBO.Listed(1, listAcc);
        accountBO.displayListAccount(jtbAccount, listAccUse);
    }//GEN-LAST:event_jlbAccTeacherMouseClicked

    private void jpnAccSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAccSearchMouseClicked
        listAccUse = accountBO.Search(txtAccSearch.getText(), listAcc);
        accountBO.displayListAccount(jtbAccount, listAccUse);
    }//GEN-LAST:event_jpnAccSearchMouseClicked

    private void jpnAccRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAccRefreshMouseClicked
        accountBO.displayListAccount(jtbAccount, listAcc);
        listAccUse = new ArrayList<>(listAcc);
        accountBO.countAcc(listAcc, jlbAccountTotal, jlbAccAdmin, jlbAccTeacher, jlbAccStudent, jlbAccOutside);
    }//GEN-LAST:event_jpnAccRefreshMouseClicked

    private void jpnAccShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnAccShowMouseClicked
        listAcc = accountBO.showAcc(jtbAccount);
        listAccUse = new ArrayList<>(listAcc);
        accountBO.countAcc(listAcc, jlbAccountTotal, jlbAccAdmin, jlbAccTeacher, jlbAccStudent, jlbAccOutside);
    }//GEN-LAST:event_jpnAccShowMouseClicked

    private void jlbAccStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAccStudentMouseClicked
        listAccUse = accountBO.Listed(2, listAcc);
        accountBO.displayListAccount(jtbAccount, listAccUse);
    }//GEN-LAST:event_jlbAccStudentMouseClicked

    private void jlbAccOutsideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAccOutsideMouseClicked
        listAccUse = accountBO.Listed(3, listAcc);
        accountBO.displayListAccount(jtbAccount, listAccUse);
    }//GEN-LAST:event_jlbAccOutsideMouseClicked

    WindowAdapter getAction = new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent e) {
            listStu = studentBO.showList(jtbStudent);
            listStuUse = new ArrayList<>(listStu);
            studentBO.count(listStuUse, jlbStudentTotal, jlbStudentMale, jlbStudentFemale, jlbIsStudy, jlbNotStudy);
        }
    };

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlbAccAdmin;
    private javax.swing.JLabel jlbAccOutside;
    private javax.swing.JLabel jlbAccRefresh;
    private javax.swing.JLabel jlbAccSearch;
    private javax.swing.JLabel jlbAccShow;
    private javax.swing.JLabel jlbAccStudent;
    private javax.swing.JLabel jlbAccTeacher;
    private javax.swing.JLabel jlbAccount;
    private javax.swing.JLabel jlbAccountTotal;
    private javax.swing.JLabel jlbIsStudy;
    private javax.swing.JLabel jlbLogout;
    private javax.swing.JLabel jlbMenuOption;
    private javax.swing.JLabel jlbNotStudy;
    private javax.swing.JLabel jlbStuReFresh;
    private javax.swing.JLabel jlbStuSearch;
    private javax.swing.JLabel jlbStuShow;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JLabel jlbStudentFemale;
    private javax.swing.JLabel jlbStudentMale;
    private javax.swing.JLabel jlbStudentTotal;
    private javax.swing.JPanel jpnAccRefresh;
    private javax.swing.JPanel jpnAccSearch;
    private javax.swing.JPanel jpnAccShow;
    private javax.swing.JPanel jpnAccount;
    private javax.swing.JPanel jpnAccountDetail;
    private javax.swing.JPanel jpnAccountOption;
    private javax.swing.JPanel jpnDefault;
    private javax.swing.JPanel jpnDefaultOption;
    private javax.swing.JPanel jpnDom;
    private javax.swing.JPanel jpnDomOption;
    private javax.swing.JPanel jpnGlobal;
    private javax.swing.JPanel jpnHandling;
    private javax.swing.JPanel jpnInformation;
    private javax.swing.JPanel jpnMenuOption;
    private javax.swing.JPanel jpnOption;
    private javax.swing.JPanel jpnStuAdd;
    private javax.swing.JPanel jpnStuDelete;
    private javax.swing.JPanel jpnStuRefresh;
    private javax.swing.JPanel jpnStuSearch;
    private javax.swing.JPanel jpnStuShow;
    private javax.swing.JPanel jpnStuUpdate;
    private javax.swing.JPanel jpnStudent;
    private javax.swing.JPanel jpnStudentDetail;
    private javax.swing.JPanel jpnStudentOption;
    private javax.swing.JPanel jpnTable;
    private javax.swing.JPanel jpnTotalInfor;
    private javax.swing.JTable jtbAccount;
    private javax.swing.JTable jtbStudent;
    private javax.swing.JTextField txtAccSearch;
    // End of variables declaration//GEN-END:variables
}
