/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import BO.AccountBO;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import util.ColorForm;
import util.DragListener;
import util.Effect;
import util.FormController;

/**
 *
 * @author Trần Việt
 */
public class SignIn extends javax.swing.JFrame {

    AccountBO accountBO = new AccountBO();
    Effect effect = new Effect();
    FormController controller = new FormController();
    boolean isDark = false;

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
        setLocationRelativeTo(null);
        SetLook();
       
    }

    public SignIn(boolean isDark) {
        initComponents();
        setLocationRelativeTo(null);
        this.isDark = isDark;
        SetLook();
       
    }

    public void SetLook() {
        ColorForm color = new ColorForm();
        color.LabelMouseEvent(isDark, jlbForgot, jlbNewAccount);
        color.PanelMouseEvent(isDark, jpnLogin);
        color.PanelBackGround(isDark, jPanel13, jpnDetails, jpnEnter, jpnForm, jpnImage, jpnLogin, jpnMain, jpnTitle);
        color.LabelBackGround(isDark, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jlbAuthor, jlbInfor);
        color.JPassWordBackGround(isDark, jPasswordField2);
        color.JTextfierdBackGround(isDark, jTextField2);
        color.JCheckBoxBackGround(isDark, jcbShow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMenu = new javax.swing.JPopupMenu();
        popLogin = new javax.swing.JMenuItem();
        popSignup = new javax.swing.JMenuItem();
        popForgot = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        popRefresh = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        popDark = new javax.swing.JMenuItem();
        popWhite = new javax.swing.JMenuItem();
        popExit = new javax.swing.JMenuItem();
        jpnMain = new javax.swing.JPanel();
        jpnImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnDetails = new javax.swing.JPanel();
        jpnTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jpnForm = new javax.swing.JPanel();
        jpnEnter = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jcbShow = new javax.swing.JCheckBox();
        jpnLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbNewAccount = new javax.swing.JLabel();
        jlbForgot = new javax.swing.JLabel();
        jlbAuthor = new javax.swing.JLabel();
        jpnSeparator1 = new javax.swing.JPanel();
        jpnSeparator2 = new javax.swing.JPanel();
        jlbInfor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuSignUp = new javax.swing.JMenuItem();
        menuForgot = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuDark = new javax.swing.JMenuItem();
        menuWhite = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        popLogin.setText("Login");
        popLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popLoginActionPerformed(evt);
            }
        });
        PopMenu.add(popLogin);

        popSignup.setText("Sign up");
        PopMenu.add(popSignup);

        popForgot.setText("Forgot password");
        PopMenu.add(popForgot);
        PopMenu.add(jSeparator2);

        popRefresh.setText("Refresh");
        PopMenu.add(popRefresh);

        jMenu4.setText("Change Background");

        popDark.setText("Dark background");
        popDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popDarkActionPerformed(evt);
            }
        });
        jMenu4.add(popDark);

        popWhite.setText("White background");
        popWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popWhiteActionPerformed(evt);
            }
        });
        jMenu4.add(popWhite);

        PopMenu.add(jMenu4);

        popExit.setText("Exit");
        popExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popExitActionPerformed(evt);
            }
        });
        PopMenu.add(popExit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jpnMain.setLayout(null);

        jpnImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnImage.setPreferredSize(new java.awt.Dimension(700, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27878ca3ab6eb32fb2982f571bbb74b1.jpg"))); // NOI18N

        javax.swing.GroupLayout jpnImageLayout = new javax.swing.GroupLayout(jpnImage);
        jpnImage.setLayout(jpnImageLayout);
        jpnImageLayout.setHorizontalGroup(
            jpnImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnImageLayout.setVerticalGroup(
            jpnImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnImageLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnMain.add(jpnImage);
        jpnImage.setBounds(0, 0, 500, 600);

        jpnDetails.setPreferredSize(new java.awt.Dimension(400, 700));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome Back Captain");

        javax.swing.GroupLayout jpnTitleLayout = new javax.swing.GroupLayout(jpnTitle);
        jpnTitle.setLayout(jpnTitleLayout);
        jpnTitleLayout.setHorizontalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTitleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jpnTitleLayout.setVerticalGroup(
            jpnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTitleLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        jpnDetails.add(jpnTitle);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("User Name:  ");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jpnEnter.add(jLabel3);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextField2.setPreferredSize(new java.awt.Dimension(200, 40));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jpnEnter.add(jTextField2);

        jPanel13.setPreferredSize(new java.awt.Dimension(390, 10));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jpnEnter.add(jPanel13);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PassWord:  ");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jpnEnter.add(jLabel5);

        jPasswordField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jPasswordField2.setEchoChar('*');
        jPasswordField2.setPreferredSize(new java.awt.Dimension(200, 40));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        jpnEnter.add(jPasswordField2);

        jcbShow.setText("Show PassWord");
        jcbShow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbShowActionPerformed(evt);
            }
        });

        jpnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnLoginMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_rounded_right_32px.png"))); // NOI18N
        jLabel4.setText("Login");

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jlbNewAccount.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbNewAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_user_26px.png"))); // NOI18N
        jlbNewAccount.setText("Sign Up!!!");
        jlbNewAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbNewAccount.setPreferredSize(new java.awt.Dimension(150, 30));
        jlbNewAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbNewAccountMouseClicked(evt);
            }
        });

        jlbForgot.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jlbForgot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/forgot_password_26px.png"))); // NOI18N
        jlbForgot.setText("Forgot PassWord?");
        jlbForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlbForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbForgotMouseClicked(evt);
            }
        });

        jlbAuthor.setText("Design By Trần Quang Việt");

        jpnSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnSeparator1Layout = new javax.swing.GroupLayout(jpnSeparator1);
        jpnSeparator1.setLayout(jpnSeparator1Layout);
        jpnSeparator1Layout.setHorizontalGroup(
            jpnSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnSeparator1Layout.setVerticalGroup(
            jpnSeparator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jpnSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnSeparator2Layout = new javax.swing.GroupLayout(jpnSeparator2);
        jpnSeparator2.setLayout(jpnSeparator2Layout);
        jpnSeparator2Layout.setHorizontalGroup(
            jpnSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnSeparator2Layout.setVerticalGroup(
            jpnSeparator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jlbInfor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jlbInfor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInfor.setText("Enter Your Account");

        javax.swing.GroupLayout jpnFormLayout = new javax.swing.GroupLayout(jpnForm);
        jpnForm.setLayout(jpnFormLayout);
        jpnFormLayout.setHorizontalGroup(
            jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFormLayout.createSequentialGroup()
                .addGroup(jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnFormLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlbAuthor))
                            .addGroup(jpnFormLayout.createSequentialGroup()
                                .addGroup(jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbForgot)
                                    .addGroup(jpnFormLayout.createSequentialGroup()
                                        .addComponent(jlbNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jpnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnFormLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnFormLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbShow)
                        .addGap(9, 9, 9)))
                .addContainerGap())
            .addGroup(jpnFormLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlbInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpnFormLayout.setVerticalGroup(
            jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFormLayout.createSequentialGroup()
                .addComponent(jpnSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbInfor, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbShow)
                .addGap(42, 42, 42)
                .addGroup(jpnFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFormLayout.createSequentialGroup()
                        .addComponent(jlbNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnFormLayout.createSequentialGroup()
                        .addComponent(jpnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(jlbForgot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jpnSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbAuthor)
                .addGap(18, 18, 18))
        );

        jpnDetails.add(jpnForm);

        jpnMain.add(jpnDetails);
        jpnDetails.setBounds(500, 0, 400, 600);

        jMenu1.setText("File");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogin);

        menuSignUp.setText("Sign up");
        menuSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSignUpActionPerformed(evt);
            }
        });
        jMenu1.add(menuSignUp);

        menuForgot.setText("Forgot password");
        jMenu1.add(menuForgot);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Refresh");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenu3.setText("Change Background");

        menuDark.setText("Dark Background");
        menuDark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDarkActionPerformed(evt);
            }
        });
        jMenu3.add(menuDark);

        menuWhite.setText("White Background");
        menuWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWhiteActionPerformed(evt);
            }
        });
        jMenu3.add(menuWhite);

        jMenu1.add(jMenu3);

        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSignUpActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (evt.getButton() == 3) {
            PopMenu.show(this, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            effect.LoadingMouse(this, true);
            accountBO.Login(this, jTextField2.getText(), jPasswordField2.getText());
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            effect.LoadingMouse(this, true);
            accountBO.Login(this, jTextField2.getText(), jPasswordField2.getText());
        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jpnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnLoginMouseClicked
        if (evt.getButton() == 1) {
            effect.LoadingMouse(this, true);
            accountBO.Login(this, jTextField2.getText(), jPasswordField2.getText());
        }
    }//GEN-LAST:event_jpnLoginMouseClicked

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        effect.LoadingMouse(this, true);
        accountBO.Login(this, jTextField2.getText(), jPasswordField2.getText());
    }//GEN-LAST:event_menuLoginActionPerformed

    private void popLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popLoginActionPerformed
        effect.LoadingMouse(this, true);
        accountBO.Login(this, jTextField2.getText(), jPasswordField2.getText());
    }//GEN-LAST:event_popLoginActionPerformed

    private void menuWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWhiteActionPerformed
        isDark = false;
        SetLook();
    }//GEN-LAST:event_menuWhiteActionPerformed

    private void menuDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDarkActionPerformed

        isDark = true;
        SetLook();
    }//GEN-LAST:event_menuDarkActionPerformed

    private void popDarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popDarkActionPerformed
        isDark = true;
        SetLook();
    }//GEN-LAST:event_popDarkActionPerformed

    private void popWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popWhiteActionPerformed
        isDark = false;
        SetLook();

    }//GEN-LAST:event_popWhiteActionPerformed

    private void jlbNewAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbNewAccountMouseClicked
        this.dispose();
        controller.show(new SignUp(isDark));
    }//GEN-LAST:event_jlbNewAccountMouseClicked

    private void jlbForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbForgotMouseClicked
        this.dispose();
        controller.show(new ForgotPass(isDark));
    }//GEN-LAST:event_jlbForgotMouseClicked

    private void jcbShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbShowActionPerformed
        if (jcbShow.isSelected()) {
            jPasswordField2.setEchoChar((char) 0);

        } else {
            jPasswordField2.setEchoChar('*');
        }
    }//GEN-LAST:event_jcbShowActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void popExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_popExitActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jTextField2.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu PopMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JCheckBox jcbShow;
    private javax.swing.JLabel jlbAuthor;
    private javax.swing.JLabel jlbForgot;
    private javax.swing.JLabel jlbInfor;
    private javax.swing.JLabel jlbNewAccount;
    private javax.swing.JPanel jpnDetails;
    private javax.swing.JPanel jpnEnter;
    private javax.swing.JPanel jpnForm;
    private javax.swing.JPanel jpnImage;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnSeparator1;
    private javax.swing.JPanel jpnSeparator2;
    private javax.swing.JPanel jpnTitle;
    private javax.swing.JMenuItem menuDark;
    private javax.swing.JMenuItem menuForgot;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuSignUp;
    private javax.swing.JMenuItem menuWhite;
    private javax.swing.JMenuItem popDark;
    private javax.swing.JMenuItem popExit;
    private javax.swing.JMenuItem popForgot;
    private javax.swing.JMenuItem popLogin;
    private javax.swing.JMenuItem popRefresh;
    private javax.swing.JMenuItem popSignup;
    private javax.swing.JMenuItem popWhite;
    // End of variables declaration//GEN-END:variables
}
