/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialog;

import BO.StudentBO;
import DAO.StudentDAO;
import entity.Student;
import javax.swing.JOptionPane;
import util.ColorForm;
import util.FormController;
import util.ImageShow;

/**
 *
 * @author Trần Việt
 */
public class StudentInfor extends javax.swing.JDialog {

    FormController controller = new FormController();
    ColorForm color = new ColorForm();
    Student stu;
    boolean type;

    /**
     * Creates new form StudentInfor
     */
    public StudentInfor(java.awt.Frame parent, boolean modal, Student stu, boolean type) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        // new ImageShow().setIcon(jLabel1, "se1032", "jpg", 155, 200);
        this.stu = stu;
        setInfor();
        setEffect();
        if (type) {
            controller.changePanel(jpnOption, "ok");
        } else {
            controller.changePanel(jpnOption, "change");
        }
    }

    public StudentInfor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String roll = "SE" + (1000 + new StudentDAO().Rollnumber());
        setLocationRelativeTo(null);
        txtRoll.setEditable(false);
        txtRoll.setText(roll);
        jcbSesion.setEnabled(false);
        jcbStatus.setEnabled(false);
        txtEmail.setEditable(false);
        txtEmail.setText(roll + "fpt.edu.vn");
        txtRoom.setEditable(false);
        setEffect();
    }

    public void setInfor() {
        jrdMale.setSelected(stu.isGender());
        txtRoll.setText(stu.getRoll().trim());
        txtRoll.setEditable(false);
        txtName.setText(stu.getName().trim());
        jTextArea1.setText(stu.getAddress().trim());
        txtDate.setText(stu.getDate().trim());
        txtPhone.setText(stu.getPhone().trim());
        txtEmail.setText(stu.getRoll().trim() + "fpt.edu.vn");
        jcbSesion.setSelectedIndex(stu.getSesion() - 1);
        jcbStatus.setSelectedIndex((stu.isStatus() ? 0 : 1));
        txtRoom.setText(stu.isInDom() ? "Có ở DOM" : "Không ở");
    }

    public void setEffect() {
        color.PanelMouseEvent(false, jpnDelete, jpnOK, jpnUpdate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpnDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoll = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jrdMale = new javax.swing.JRadioButton();
        jrdFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jpnMoreInfor = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcbStatus = new javax.swing.JComboBox<>();
        jcbSesion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jpnOption = new javax.swing.JPanel();
        jpnAccept = new javax.swing.JPanel();
        jpnOK = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpnChange = new javax.swing.JPanel();
        jpnUpdate = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpnDelete = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 790));

        jpnDetail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnDetail.setPreferredSize(new java.awt.Dimension(700, 600));
        jpnDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnDetail.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 32, 155, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Roll number:");
        jpnDetail.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 80, 35));

        txtRoll.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnDetail.add(txtRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 207, 35));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnDetail.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 207, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Full Name:");
        jpnDetail.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 80, 35));

        txtDate.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnDetail.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 207, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Date of Birth:");
        jpnDetail.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 88, 35));

        txtPhone.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jpnDetail.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 207, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address:");
        jpnDetail.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 81, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Gender:");
        jpnDetail.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 80, 35));

        buttonGroup1.add(jrdMale);
        jrdMale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrdMale.setText("Male");
        jpnDetail.add(jrdMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 35));

        buttonGroup1.add(jrdFemale);
        jrdFemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jrdFemale.setSelected(true);
        jrdFemale.setText("Female");
        jpnDetail.add(jrdFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, 35));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jpnDetail.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 520, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Status:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Room:");

        txtRoom.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtRoom.setText("Không ở");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sesion:");

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang học", "Đã nghỉ" }));

        jcbSesion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        javax.swing.GroupLayout jpnMoreInforLayout = new javax.swing.GroupLayout(jpnMoreInfor);
        jpnMoreInfor.setLayout(jpnMoreInforLayout);
        jpnMoreInforLayout.setHorizontalGroup(
            jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMoreInforLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMoreInforLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(64, 64, 64)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMoreInforLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jcbSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRoom)
                    .addComponent(jcbStatus, 0, 207, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jpnMoreInforLayout.setVerticalGroup(
            jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMoreInforLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnMoreInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jpnDetail.add(jpnMoreInfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 660, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        jpnDetail.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, 35));

        getContentPane().add(jpnDetail, java.awt.BorderLayout.CENTER);

        jpnOption.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnOption.setPreferredSize(new java.awt.Dimension(650, 150));
        jpnOption.setLayout(new java.awt.CardLayout());

        jpnAccept.setPreferredSize(new java.awt.Dimension(700, 150));

        jpnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnOKMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("OK");

        javax.swing.GroupLayout jpnOKLayout = new javax.swing.GroupLayout(jpnOK);
        jpnOK.setLayout(jpnOKLayout);
        jpnOKLayout.setHorizontalGroup(
            jpnOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnOKLayout.setVerticalGroup(
            jpnOKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnOKLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnAcceptLayout = new javax.swing.GroupLayout(jpnAccept);
        jpnAccept.setLayout(jpnAcceptLayout);
        jpnAcceptLayout.setHorizontalGroup(
            jpnAcceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAcceptLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jpnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
        jpnAcceptLayout.setVerticalGroup(
            jpnAcceptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAcceptLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jpnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jpnOption.add(jpnAccept, "ok");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Update");

        javax.swing.GroupLayout jpnUpdateLayout = new javax.swing.GroupLayout(jpnUpdate);
        jpnUpdate.setLayout(jpnUpdateLayout);
        jpnUpdateLayout.setHorizontalGroup(
            jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUpdateLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnUpdateLayout.setVerticalGroup(
            jpnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        jpnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnDeleteMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Delete");

        javax.swing.GroupLayout jpnDeleteLayout = new javax.swing.GroupLayout(jpnDelete);
        jpnDelete.setLayout(jpnDeleteLayout);
        jpnDeleteLayout.setHorizontalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jpnDeleteLayout.setVerticalGroup(
            jpnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnChangeLayout = new javax.swing.GroupLayout(jpnChange);
        jpnChange.setLayout(jpnChangeLayout);
        jpnChangeLayout.setHorizontalGroup(
            jpnChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChangeLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jpnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jpnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jpnChangeLayout.setVerticalGroup(
            jpnChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChangeLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jpnChangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jpnOption.add(jpnChange, "change");

        getContentPane().add(jpnOption, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnOKMouseClicked
        if (type) {
            JOptionPane.showConfirmDialog(this, "Update");
        } else {
            new StudentBO().prepapeAdd(this, jTextArea1, jrdMale, txtRoll, txtName, txtDate, txtPhone);
        }
    }//GEN-LAST:event_jpnOKMouseClicked

    private void jpnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnDeleteMouseClicked
        new StudentBO().deleteStudent(txtRoll.getText().trim());
        this.dispose();
    }//GEN-LAST:event_jpnDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcbSesion;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JPanel jpnAccept;
    private javax.swing.JPanel jpnChange;
    private javax.swing.JPanel jpnDelete;
    private javax.swing.JPanel jpnDetail;
    private javax.swing.JPanel jpnMoreInfor;
    private javax.swing.JPanel jpnOK;
    private javax.swing.JPanel jpnOption;
    private javax.swing.JPanel jpnUpdate;
    private javax.swing.JRadioButton jrdFemale;
    private javax.swing.JRadioButton jrdMale;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRoll;
    private javax.swing.JTextField txtRoom;
    // End of variables declaration//GEN-END:variables
}
